# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'COVID' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for COVID
  pod 'Firebase'
  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'

  pod 'Alamofire'
  pod 'HapticButton'
  pod 'SnapKit'
  pod 'CodableFirebase'
end
